In [62]:
import pandas as pd
import numpy as np
import seaborn as sns #visualisation
import matplotlib.pyplot as plt #visualisation
%matplotlib inline 
sns.set(color_codes=True)

In [63]:
harms = pd.read_csv('substance_harm_data.csv')
waste = pd.read_csv('wastewater_data.csv')

In [64]:
harms.head()

,Substance,Source,Specific_Measure,Type_Event,Region,PRUID,Time_Period,Year_Quarter,Aggregator,Disaggregator,Unit,Value
0,Opioids,Deaths,Overall numbers,Total apparent opioid toxicity deaths,Canada,1,By year,2016,NaN,NaN,Crude rate,7.8
1,Opioids,Deaths,Overall numbers,Total apparent opioid toxicity deaths,Canada,1,By year,2016,NaN,NaN,Number,2827
2,Opioids,Deaths,Overall numbers,Total apparent opioid toxicity deaths,Canada,1,By year,2016,NaN,NaN,Age-adjusted rate,7.8
3,Opioids,Deaths,Overall numbers,Total apparent opioid toxicity deaths,Canada,1,By year,2017,NaN,NaN,Crude rate,10.7
4,Opioids,Deaths,Overall numbers,Total apparent opioid toxicity deaths,Canada,1,By year,2017,NaN,NaN,Number,3922

In [65]:
waste.head()

,REF_DATE,GEO,DGUID,Measure,Characteristics,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,Mar-19,"Weighted average, cities measured",NaN,THC-COOH (Cannabis metabolite),Load per capita (grams per one million people ...,Grams per one million people per day,411,units,0,v1277978059,1.1.1,263.21,NaN,NaN,NaN,2
1,Mar-19,"Weighted average, cities measured",NaN,THC-COOH (Cannabis metabolite),"Lower bound of the 95% confidence interval, lo...",Grams per one million people per day,411,units,0,v1277978060,1.1.2,224.66,NaN,NaN,NaN,2
2,Mar-19,"Weighted average, cities measured",NaN,THC-COOH (Cannabis metabolite),"Upper bound of the 95% confidence interval, lo...",Grams per one million people per day,411,units,0,v1277978061,1.1.3,301.75,NaN,NaN,NaN,2
3,Mar-19,"Weighted average, cities measured",NaN,THC-COOH (Cannabis metabolite),"Standard error, load per capita",Grams per one million people per day,411,units,0,v1277978062,1.1.4,13.74,NaN,NaN,NaN,2
4,Mar-19,"Weighted average, cities measured",NaN,THC-COOH (Cannabis metabolite),"Imputation rate, load per capita",Percentage,242,units,0,v1277978063,1.1.5,11.00,NaN,NaN,NaN,0

In [66]:
waste.shape
waste.info()
waste.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11088 entries, 0 to 11087
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         11088 non-null  object
 1   GEO              11088 non-null  object
 2   DGUID            0 non-null      float64
 3   Measure          11088 non-null  object
 4   Characteristics  11088 non-null  object
 5   UOM              11088 non-null  object
 6   UOM_ID           11088 non-null  int64
 7   SCALAR_FACTOR    11088 non-null  object
 8   SCALAR_ID        11088 non-null  int64
 9   VECTOR           11088 non-null  object
 10  COORDINATE       11088 non-null  object
 11  VALUE            9665 non-null   float64
 12  STATUS           2142 non-null   object
 13  SYMBOL           0 non-null      float64
 14  TERMINATED       0 non-null      float64
 15  DECIMALS         11088 non-null  int64
dtypes: float64(4), int64(3), object(9)
memory usage: 1.4+ MB

REF_DATE            object
GEO                 object
DGUID              float64
Measure             object
Characteristics     object
UOM                 object
UOM_ID               int64
SCALAR_FACTOR       object
SCALAR_ID            int64
VECTOR              object
COORDINATE          object
VALUE              float64
STATUS              object
SYMBOL             float64
TERMINATED         float64
DECIMALS             int64
dtype: object

In [67]:
harms.shape
harms.info()
harms.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12099 entries, 0 to 12098
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Substance         12099 non-null  object
 1   Source            12099 non-null  object
 2   Specific_Measure  12099 non-null  object
 3   Type_Event        12099 non-null  object
 4   Region            12099 non-null  object
 5   PRUID             12099 non-null  int64
 6   Time_Period       12099 non-null  object
 7   Year_Quarter      12099 non-null  object
 8   Aggregator        8161 non-null   object
 9   Disaggregator     8161 non-null   object
 10  Unit              12099 non-null  object
 11  Value             11559 non-null  object
dtypes: int64(1), object(11)
memory usage: 1.1+ MB

Substance           object
Source              object
Specific_Measure    object
Type_Event          object
Region              object
PRUID                int64
Time_Period         object
Year_Quarter        object
Aggregator          object
Disaggregator       object
Unit                object
Value               object
dtype: object

In [68]:
#percentage of na
waste.isnull().sum() / waste.shape[0] * 100

REF_DATE             0.000000
GEO                  0.000000
DGUID              100.000000
Measure              0.000000
Characteristics      0.000000
UOM                  0.000000
UOM_ID               0.000000
SCALAR_FACTOR        0.000000
SCALAR_ID            0.000000
VECTOR               0.000000
COORDINATE           0.000000
VALUE               12.833694
STATUS              80.681818
SYMBOL             100.000000
TERMINATED         100.000000
DECIMALS             0.000000
dtype: float64

In [69]:
waste = waste.drop(['SYMBOL', 'TERMINATED', 'DGUID'], axis=1)

In [70]:
#percentage of na
harms.isnull().sum() / harms.shape[0] * 100

Substance            0.000000
Source               0.000000
Specific_Measure     0.000000
Type_Event           0.000000
Region               0.000000
PRUID                0.000000
Time_Period          0.000000
Year_Quarter         0.000000
Aggregator          32.548144
Disaggregator       32.548144
Unit                 0.000000
Value                4.463179
dtype: float64

In [71]:
print(waste.isnull().sum())

REF_DATE              0
GEO                   0
Measure               0
Characteristics       0
UOM                   0
UOM_ID                0
SCALAR_FACTOR         0
SCALAR_ID             0
VECTOR                0
COORDINATE            0
VALUE              1423
STATUS             8946
DECIMALS              0
dtype: int64

In [72]:
print(harms.isnull().sum())

Substance              0
Source                 0
Specific_Measure       0
Type_Event             0
Region                 0
PRUID                  0
Time_Period            0
Year_Quarter           0
Aggregator          3938
Disaggregator       3938
Unit                   0
Value                540
dtype: int64